FULL_STACK_DEVELOPER = [
    "JAVASCRIPT", "TYPESCRIPT",
    "REACT", "ANGULAR", "VUE",
    "NODE_JS", "DJANGO", "SPRING_BOOT",
    "SQL", "NOSQL", "POSTGRESQL",
    "REST_API",
    "GIT",
]

MACHINE_LEARNING_ENGINEER = [
    "PYTHON",
    "PANDAS", "NUMPY",
    "SCIKIT_LEARN", "TENSORFLOW", "PYTORCH",
    "ML_MODEL_DEVELOPMENT",
    "SQL",
    "GIT",
]

DATA_SCIENTIST = [
    "PYTHON", "R",
    "PANDAS", "NUMPY",
    "SCIKIT_LEARN", "MATPLOTLIB", "SEABORN",
    "STATISTICS",
    "SQL",
    "GIT",
]

SOFTWARE_ARCHITECT = [
    "JAVA", "CSHARP", "PYTHON",
    "DESIGN_PATTERNS", "MICROSERVICES",
    "DOCKER", "KUBERNETES", "AWS", "AZURE", "GCP",
    "REST_API", "GRAPHQL",
    "SQL", "NOSQL",
    "GIT",
]

PROFILE_ORDER = {
    "FULL_STACK_DEVELOPER": FULL_STACK_DEVELOPER,
    "MACHINE_LEARNING_ENGINEER": MACHINE_LEARNING_ENGINEER,
    "DATA_SCIENTIST": DATA_SCIENTIST,
    "SOFTWARE_ARCHITECT": SOFTWARE_ARCHITECT,
}
